version: '3'

services:
  client-frontend:
    container_name: front
    mem_limit: "1g"
    mem_reservation: "256m"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
